### ISSUE TITLE
Durable was added only in the main code, but not in the release

### ISSUE THREAD

**Issue by gustavostz** [eferraris/rabbit-sender#1]
Hello! :)

The param "Durable" was added only in the main code, but not in the release. I think just generating another release with the main code will work with this new param. 

Evidence:

Action:
![image](https://user-images.githubusercontent.com/48111506/161404609-1b482e4e-44ae-448c-824a-5f7bcf810d82.png)

Release Code:

![image](https://user-images.githubusercontent.com/48111506/161404533-c968e7a1-4ac7-46fe-b6f1-6b529df97035.png)

Code in the main branch:

![image](https://user-images.githubusercontent.com/48111506/161404545-8069a696-d9f9-4624-8650-1cfe3f7791ef.png)

By the way, great solution 💯

**Comment by eferraris** [comment]
Good to know that this action is useful for you. I'll be resolving this one today. Thank you!

**Comment by eferraris** [comment]
It's done, i've just made a new release (v1.1)
